"""update product

Revision ID: 1fd6c85271e7
Revises: dc25df0efafb
Create Date: 2023-12-09 13:45:13.896713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd6c85271e7'
down_revision: Union[str, None] = 'dc25df0efafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_author_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_author_id_fkey', 'products', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
