"""init

Revision ID: 8d0a5eb26681
Revises: 426733bb0965
Create Date: 2023-10-23 17:15:53.000270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d0a5eb26681'
down_revision: Union[str, None] = '426733bb0965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('born', sa.DateTime(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('products_count', sa.Integer(), nullable=True),
    sa.Column('translated_languages', sa.JSON(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.drop_constraint('products_author_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key('products_author_id_fkey', 'products', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_author_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key('products_author_id_fkey', 'products', 'shop_owners', ['author_id'], ['id'])
    op.drop_table('authors')
    # ### end Alembic commands ###
