"""remove show customer

Revision ID: f2e2361c1472
Revises: f70c025264cc
Create Date: 2023-12-03 14:56:50.650533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e2361c1472'
down_revision: Union[str, None] = 'f70c025264cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_shop_id_fkey', 'customers', type_='foreignkey')
    op.drop_column('customers', 'shop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('customers_shop_id_fkey', 'customers', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###
