"""add image to product

Revision ID: 56fc037b9c06
Revises: dc469df7810e
Create Date: 2023-10-07 10:42:01.264793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fc037b9c06'
down_revision: Union[str, None] = 'dc469df7810e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'image_id')
    # ### end Alembic commands ###
