"""udate shop settings

Revision ID: 24316106db73
Revises: f3b35ca7d64c
Create Date: 2023-10-07 17:37:28.806303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24316106db73'
down_revision: Union[str, None] = 'f3b35ca7d64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shops', 'shop_settings', ['settings_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'settings_id')
    # ### end Alembic commands ###
