"""update relations

Revision ID: dae032d763ed
Revises: dd80ef91db95
Create Date: 2023-11-25 19:08:43.497381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae032d763ed'
down_revision: Union[str, None] = 'dd80ef91db95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key('customer_address_fkey', 'customers', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_address_fkey', 'customers', type_='foreignkey')
    op.drop_column('customers', 'address_id')
    # ### end Alembic commands ###
