"""update product

Revision ID: 5b5475d051ea
Revises: 1fd6c85271e7
Create Date: 2023-12-09 13:47:39.108244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b5475d051ea'
down_revision: Union[str, None] = '1fd6c85271e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'authors',
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
        sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('quote', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('born', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('languages', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('products_count', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('translated_languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('cover_image_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                  autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                  autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['cover_image_id'], ['images.id'], name='authors_cover_image_id_fkey'),
        sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='authors_image_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='authors_pkey'),
        sa.UniqueConstraint('slug', name='authors_slug_key')
    )
    # ### end Alembic commands ###
