"""update product

Revision ID: 9b7c626ea7a4
Revises: e0a74c00e81f
Create Date: 2023-12-09 13:42:36.729302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9b7c626ea7a4'
down_revision: Union[str, None] = 'e0a74c00e81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'min_price',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('products', 'max_price',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.drop_constraint('products_sku_key', 'products', type_='unique')
    op.drop_column('products', 'height')
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'manufacturer_id')
    op.drop_column('products', 'in_stock')
    op.drop_column('products', 'external_product_url')
    op.drop_column('products', 'length')
    op.drop_column('products', 'width')
    op.drop_column('products', 'is_taxable')
    op.drop_column('products', 'external_product_button_text')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products',
                  sa.Column('external_product_button_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_taxable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('width', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('length', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('external_product_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('manufacturer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('product_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('height', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('products_sku_key', 'products', ['sku'])
    op.alter_column('products', 'max_price',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('products', 'min_price',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    # ### end Alembic commands ###
