"""remove shop owner

Revision ID: f70c025264cc
Revises: 017e27b97ce6
Create Date: 2023-12-03 10:37:22.821501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f70c025264cc'
down_revision: Union[str, None] = '017e27b97ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shops_owner_id_fkey', 'shops', type_='foreignkey')
    op.drop_table('shop_owners')
    op.create_foreign_key('shop_owner_fkey', 'shops', 'customers', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shop_owner_fkey', 'shops', type_='foreignkey')
    op.create_foreign_key('shops_owner_id_fkey', 'shops', 'shop_owners', ['owner_id'], ['id'])
    op.create_table(
        'shop_owners',
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False,
                  nullable=True),
        sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                  autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                  autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='shop_owners_profile_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='shop_owners_pkey')
    )
    # ### end Alembic commands ###
