"""update address relation

Revision ID: 1781784bb514
Revises: dae032d763ed
Create Date: 2023-11-25 20:06:50.713810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1781784bb514'
down_revision: Union[str, None] = 'dae032d763ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_address_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key('customer_addresses_fkey', 'customers', 'customer_addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_addresses_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key('customer_address_fkey', 'customers', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###
