"""category type

Revision ID: c00047f4f6e9
Revises: d4ed36dfee2e
Create Date: 2023-10-22 12:41:16.208844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c00047f4f6e9'
down_revision: Union[str, None] = 'd4ed36dfee2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_types', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('category_types', sa.Column('icon', sa.String(), nullable=True))
    op.create_unique_constraint('category_type_slug', 'category_types', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_type_slug', 'category_types', type_='unique')
    op.drop_column('category_types', 'icon')
    op.drop_column('category_types', 'slug')
    # ### end Alembic commands ###
