"""add sub to customer

Revision ID: dd80ef91db95
Revises: 23188c7911e6
Create Date: 2023-11-13 22:47:56.379712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd80ef91db95'
down_revision: Union[str, None] = '23188c7911e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('sub', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'sub')
    # ### end Alembic commands ###
