"""update permissions

Revision ID: 017e27b97ce6
Revises: 1781784bb514
Create Date: 2023-12-03 09:10:54.402756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017e27b97ce6'
down_revision: Union[str, None] = '1781784bb514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permissions_guard_name_key', 'permissions', type_='unique')
    op.create_unique_constraint('permission_uniques_name', 'permissions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permission_uniques_name', 'permissions', type_='unique')
    op.create_unique_constraint('permissions_guard_name_key', 'permissions', ['guard_name'])
    # ### end Alembic commands ###
